//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCLProject.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BCLProject.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder ({0}) from list in cfg was added to list for monitoring.
        /// </summary>
        internal static string AddFolderToCollection {
            get {
                return ResourceManager.GetString("AddFolderToCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule ({0}) from cfg was added to list of rules..
        /// </summary>
        internal static string AddRuleToCollection {
            get {
                return ResourceManager.GetString("AddRuleToCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config not found!.
        /// </summary>
        internal static string ConfigNotFounded {
            get {
                return ResourceManager.GetString("ConfigNotFounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not founded..
        /// </summary>
        internal static string FileNotFounded {
            get {
                return ResourceManager.GetString("FileNotFounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founded template ({0}).
        /// </summary>
        internal static string FoundedTemplate {
            get {
                return ResourceManager.GetString("FoundedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello!.
        /// </summary>
        internal static string Hello_string {
            get {
                return ResourceManager.GetString("Hello_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule was founded..
        /// </summary>
        internal static string MatchWithRule {
            get {
                return ResourceManager.GetString("MatchWithRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file ({0}) was moved to folder ({1}).
        /// </summary>
        internal static string MovedTemplate {
            get {
                return ResourceManager.GetString("MovedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rule was not founded..
        /// </summary>
        internal static string NoMatchedRule {
            get {
                return ResourceManager.GetString("NoMatchedRule", resourceCulture);
            }
        }
    }
}
